### ISSUE TITLE
Cannot read property 'self' of undefined

### ISSUE THREAD

**Issue by subotkevic** [milroyfraser/sarala#7]
When trying to save updated resource:
`Uncaught TypeError: Cannot read property 'self' of undefined` in `Model.js:223`

Looks like it tries to access `url: this.links.self,`, but my API response does not contain `links.self` when I fetch resources with `all()` or `paginate()`. 

I think we should try to get/build PUT url different way.

What do you think?

**Comment by subotkevic** [comment]
Or maybe we should be able to define or override that URL in the model itself somehow?

**Comment by subotkevic** [comment]
Currently I have temp solution from client side:

In my base model I just implemented `update()` method like this:
```js
update() {
  return this.makePersistRequest({
    url: this.resourceUrl() + this.data().id,
    method: 'PUT',
    data: this.serialize(this.data())   
  })
}
```

So basically the same method just with different `url` element.

**Comment by subotkevic** [comment]
More news... Looks like `_delete()` method using self URL the same way, so currently I came across with something like this is my Base Model:

```js
update() {
    this.buildSelf()
    super.update()
  }

  _delete() {
    this.buildSelf()
    super._delete()
  }

  buildSelf() {
    const self = this.resourceUrl() + this.data().id

    if (this.hasOwnProperty('links')) {
      if (! this.links.hasOwnProperty('self')) {
        this.links.self = self
      }
    } else {
      this.links = { self }
    }
  }
```

**Comment by milroyfraser** [comment]
Hi @subotkevic thank you very much for constructive comments. 
Fixed on 0.3.9 ✌️

**Comment by subotkevic** [comment]
Well, thank you for resolving this issue. 

Not an issue though, but now it will be much more reusable.

**Comment by subotkevic** [comment]
By the way,

I checked your commits on that, and I can tell you that approach is good, but you forgot to handle the case when api will provide self url, so I think you need to additionally check for self url in the model, and if it does not exist, then use current approach.

**Comment by milroyfraser** [comment]
@subotkevic Thanks for the input.
 
Sarata expects api to follow [{JSON:API} Recommendations](https://jsonapi.org/recommendations/#urls). In that case this is always the same.

But I agree with your point, as an improvement we can check it before generate it.
